/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Battleship;

import java.util.Scanner;

public class App {
    public void run() {
        Scanner sc = new Scanner(System.in);
        GameCore game = new GameCore();
        game.setShips(sc);
        game.startGame(sc);
    }

    public static void main(String[] args) {
        new App().run();
    }
}
